name: lint, test, build
run-name: ${{github.actor}} is learning github actions
on:
    push:
        branches: [main]
    pull_request: 
        branches: [main]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/seup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: install
              run: npm install
            - name: build production
              run: npm run build:prod
            - name: linting typescript
              run: npm run eslint
            - name: linting styles
              run: npm run stylelint
            - name: unit tests
              run: npm run test
